export const MANAGED_OVERVIEW = {
  eyebrow: 'Managed Services Overview',
  title: 'Technology Operations. Consulting Governance.',
  lead: 'Ongoing management of database, cloud, security, and platform environments — delivered under the architecture standards, governance frameworks, and operational controls defined by senior practitioners.',
  stats: [
    { value: 'SME', label: 'Led Standards Definition' },
    { value: '4', label: 'Service Domains' },
    { value: 'Zero', label: 'Governance Gaps' },
    { value: '∞', label: 'Continuous Optimisation' },
  ],
  difference: {
    eyebrow: 'The Gigamatics Difference',
    title: 'How Managed Services at Gigamatics Are Different.',
    body: 'Most managed services are either tool-focused outsourcing or headcount substitution. Neither model delivers the governance, standards, or senior oversight that complex enterprise environments actually require.',
    columns: [
      {
        title: 'Traditional MSP',
        subtitle: 'Tool-focused outsourcing',
        items: [
          'SLA-driven, reactive incident response',
          'Tool dashboards without architectural context',
          'No standards ownership or documentation',
          'Escalation chains replace accountability',
          'Generic runbooks not tailored to your environment',
          'Firefighting over forward planning',
        ],
      },
      {
        title: 'Staff Augmentation',
        subtitle: 'Body-shop model',
        items: [
          'Individual capability without system governance',
          'No defined standards or delivery framework',
          'Knowledge leaves when the resource leaves',
          'No continuity, documentation, or oversight',
          'Execution without architectural alignment',
          'Client carries all governance responsibility',
        ],
      },
      {
        title: 'Gigamatics Model',
        subtitle: 'Consulting-governed operations',
        highlight: true,
        items: [
          'Architecture standards defined by subject matter experts',
          'Day-to-day execution under structured senior oversight',
          'Governance frameworks documented and version-controlled',
          'Proactive optimization, not just incident response',
          'Continuous alignment with your compliance posture',
          'Single accountable point of contact throughout',
        ],
      },
    ],
  },
  domains: [
    {
      num: '01',
      title: 'Managed Database Services',
      body: 'Architecture-governed database administration, monitoring, and optimization for Oracle, SQL Server, PostgreSQL, and MySQL environments — under defined performance standards, change control, and availability frameworks.',
      to: '/managed-services/database',
      items: [
        'Performance monitoring & capacity governance',
        'Backup, recovery & DR orchestration',
        'Patching under defined change control',
        'Query performance optimization',
        'HA/RAC configuration management',
        'Proactive health assessments & reporting',
      ],
    },
    {
      num: '02',
      title: 'Managed Cloud Operations',
      body: 'Ongoing governance and operational management of AWS, Azure, and GCP environments — covering cost controls, configuration standards, security posture, and continuous optimization.',
      to: '/managed-services/cloud',
      items: [
        'Cloud cost governance & FinOps oversight',
        'Configuration & drift management',
        'Infrastructure-as-code standards enforcement',
        'Platform availability & incident management',
        'Security posture monitoring',
        'Monthly optimization reviews',
      ],
    },
    {
      num: '03',
      title: 'Managed Security Operations',
      body: 'Security architecture standards defined by practitioners with compliance and threat modelling experience. Execution covers access governance, vulnerability management, and continuous monitoring.',
      to: '/managed-services/security',
      items: [
        'Access governance & IAM policy management',
        'Vulnerability assessment & remediation tracking',
        'Compliance posture monitoring (ISO 27001, SOC 2, PCI)',
        'Security incident response coordination',
        'Patch governance across managed estate',
        'Periodic architecture reviews',
      ],
    },
    {
      num: '04',
      title: 'Platform Reliability & SRE',
      body: 'SLO-governed reliability operations for Kubernetes environments, microservice platforms, and critical production infrastructure — with structured reporting on trends, incidents, and capacity.',
      to: '/managed-services/platform',
      items: [
        'SLO definition & reliability governance',
        'Kubernetes cluster management & operations',
        'Observability stack management',
        'On-call coordination & incident response',
        'Capacity planning & performance trending',
        'Post-incident review & RCA governance',
      ],
    },
  ],
  onboarding: [
    { num: '01', title: 'Governance Definition', body: 'Standards, controls, and operational policies that govern the engagement — architecture standards, SLOs, change control, escalation frameworks, and compliance requirements — documented before operational handover.' },
    { num: '02', title: 'Standards Alignment', body: 'Existing documentation, configurations, and practices are reviewed and aligned to defined governance frameworks. Gaps are identified. Runbooks are authored against actual environment specifics.' },
    { num: '03', title: 'Operational Handover', body: 'Monitoring, alerting, and operational tooling are configured against defined standards. Practitioners are briefed. Transition to ongoing management is governed, documented, and verified.' },
    { num: '04', title: 'Continuous Optimization', body: 'Structured periodic reviews — assessing performance trends, optimization opportunities, evolving compliance requirements, and architectural decisions that affect long-term health.' },
  ],
  faqs: [
    { q: 'How long does onboarding take?', a: 'Typically 2–4 weeks depending on environment complexity. We don’t compress this phase — proper governance definition takes the time it takes.' },
    { q: 'What if we have existing documentation?', a: 'Existing runbooks and architecture docs are reviewed and incorporated. We assess gaps and bring documentation to the standard our governance model requires.' },
    { q: 'Who owns the governance documentation?', a: 'You do. All governance frameworks, runbooks, and operational standards we produce are your intellectual property and remain with you.' },
    { q: 'What do periodic reviews include?', a: 'Monthly: operational metrics and incident review. Quarterly: architecture alignment, optimization opportunities, and roadmap inputs. Annual: full governance framework review.' },
    { q: 'What happens if we decide to transition away?', a: 'All governance frameworks, runbooks, configuration standards, and documentation remain with you. If required, we support a structured transition to your internal team or another provider.' },
    { q: 'How is accountability structured?', a: 'Each engagement operates under a defined governance model with a single accountable lead. Escalation paths, decision rights, and review forums are documented upfront.' },
  ],
};

export const MANAGED_SERVICES = [
  {
    slug: 'database',
    path: '/managed-services/database',
    title: 'Managed Database Operations',
    cardBody: 'Monitoring, performance tuning, patching, backup governance and platform stability across enterprise databases.',
    lead: 'Operate Enterprise Databases with Confidence',
    intro: 'Senior database engineers, running on a defined service model. Monitoring, performance, patching, backup governance, access control, and compliance support — across every major database platform, delivered as a fully managed service.',
    pillarsIntro: 'Every Gigamatics database managed service is built around defined operational pillars. Coverage is comprehensive, governance-driven, and adapted to your specific database environment and SLA requirements.',
    pillars: [
      { title: 'Monitoring & Health Management', body: 'Continuous 24×7 monitoring of database availability, resource utilisation, connection health, and performance baselines.', includes: ['Real-time availability monitoring', 'Proactive alert triage', 'Scheduled health checks', 'Utilisation trending'] },
      { title: 'Performance Tuning & Optimisation', body: 'Systematic analysis and tuning of slow queries, indexes, execution plans, and workload patterns.', includes: ['Query and plan optimisation', 'Index design and rebuilds', 'Workload profiling', 'Configuration tuning'] },
      { title: 'Patch Management & Version Lifecycle', body: 'Structured patch planning, testing, and deployment — keeping databases current, secure, and stable.', includes: ['Risk-qualified scheduling', 'Staging before production', 'Version upgrade planning', 'EOL tracking'] },
      { title: 'Backup Governance & Recovery Testing', body: 'Automated backups per defined policy, with completion verification and periodic restore validation.', includes: ['Automated backup execution', 'Retention compliance', 'Monthly restore validation', 'Recovery runbooks'] },
      { title: 'High Availability & Failover Validation', body: 'Design verification and regular testing of HA configurations under real failure conditions.', includes: ['HA architecture review', 'Replication health monitoring', 'Scheduled failover tests', 'Failover runbooks'] },
      { title: 'Incident Management & RCA', body: 'Structured incident response with defined severity levels, escalation paths, and documented root cause reports.', includes: ['P1/P2/P3 classification', 'Senior DBA escalation', 'Post-incident RCA', 'Recurrence prevention'] },
    ],
    engagementPhases: [
      { title: 'Dedicated Senior DBA Ownership', body: 'A named senior DBA manages your environment — no generic support pool.' },
      { title: 'Structured Onboarding & Baseline', body: 'Documented assessment of architecture, configuration, backups, and risks before monitoring goes live.' },
      { title: 'Defined SLAs & Measured Accountability', body: 'Contractually defined response and availability targets with monthly performance reporting.' },
      { title: 'Monthly Operational Reporting', body: 'Structured reports covering health, incidents, patches, capacity, and recommended actions.' },
      { title: 'Advisory Included', body: 'Architectural guidance and strategic input are part of the service — not billed separately.' },
    ],
    principles: [
      { title: 'Senior DBAs, Not Support Analysts', body: 'Every environment is managed by experienced practitioners who have designed and operated production databases at enterprise scale.' },
      { title: 'Proactive, Not Reactive', body: 'We identify and resolve performance bottlenecks, backup failures, and capacity risks before they become incidents.' },
      { title: 'Consulting Is Part of the Service', body: 'Technology advisory and migration planning are included — your DBA team is also your database advisor.' },
      { title: 'Governance-Governed Operations', body: 'Every procedure is documented, every change is governed, every incident is reported.' },
    ],
  },
  {
    slug: 'cloud',
    path: '/managed-services/cloud',
    title: 'Managed Cloud & Infrastructure Operations',
    cardBody: 'Operational oversight for cloud environments including cost governance, configuration management, and reliability.',
    lead: 'Run Cloud Infrastructure with Operational Excellence',
    intro: 'Senior cloud engineers running your infrastructure on a defined service model. Monitoring, lifecycle management, cost governance, security drift detection, capacity planning, and compliance support — across AWS, Azure, GCP, Oracle Cloud, and hybrid environments.',
    pillarsIntro: 'Every Gigamatics cloud managed service is structured around defined operational pillars — each governed, documented, and adapted to your environment, scale, and compliance obligations.',
    pillars: [
      { title: 'Infrastructure Monitoring & Health', body: 'Continuous 24×7 monitoring of compute, storage, networking, and platform services with proactive alerting.', includes: ['Availability monitoring', 'Alert triage', 'Health checks', 'Anomaly detection'] },
      { title: 'Lifecycle Management', body: 'Structured management of compute, storage, and network resources from provisioning through decommissioning.', includes: ['Resource lifecycle', 'Storage tier management', 'Network governance', 'OS and image currency'] },
      { title: 'IaC & Configuration Management', body: 'Infrastructure-as-Code governed provisioning ensuring environments are consistent and free from drift.', includes: ['Terraform / CloudFormation / Bicep', 'Drift detection', 'Change management', 'Environment standardisation'] },
      { title: 'Cost Monitoring & FinOps', body: 'Continuous cloud cost monitoring with rightsizing, waste elimination, and budget governance.', includes: ['Cost anomaly alerting', 'Waste identification', 'Rightsizing sprints', 'Commitment utilisation'] },
      { title: 'Security Drift Detection', body: 'Continuous monitoring of cloud security posture against defined baselines.', includes: ['CSPM integration', 'Public exposure alerting', 'IAM privilege drift', 'Encryption reviews'] },
      { title: 'Incident Management', body: 'Structured incident response with defined severity classifications and documented RCA.', includes: ['P1/P2/P3 SLAs', 'Senior engineer escalation', 'Post-incident RCA', 'Failure pattern analysis'] },
    ],
    engagementPhases: [
      { title: 'Named Senior Cloud Engineer Ownership', body: 'Your environment is assigned to a named senior engineer — not a generic NOC team.' },
      { title: 'Structured Onboarding & Baseline', body: 'Comprehensive cloud estate assessment before operations begin.' },
      { title: 'Contractually Defined SLAs', body: 'Response times and availability targets are contractually bound and actively measured.' },
      { title: 'Monthly Operational & Cost Reports', body: 'Infrastructure health, incidents, security posture, cost trends, and capacity outlook.' },
      { title: 'Architecture Advisory Included', body: 'Cloud architecture guidance and FinOps advisory are part of the engagement.' },
    ],
    principles: [
      { title: 'Senior Engineers, Not NOC Analysts', body: 'Managed by engineers who have designed, migrated, and operated production infrastructure at enterprise scale.' },
      { title: 'Proactive by Design', body: 'Monitoring, drift detection, and capacity reviews surface problems before they become incidents.' },
      { title: 'Cost Governance Is Part of Operations', body: 'FinOps is embedded in day-to-day operations — not a separate engagement.' },
      { title: 'Governance That Scales With You', body: 'As your estate grows, governance frameworks and operational procedures scale with it.' },
    ],
  },
  {
    slug: 'security',
    path: '/managed-services/security',
    title: 'Managed Security & Compliance Operations',
    cardBody: 'Continuous posture monitoring, vulnerability management, access controls, and governance alignment.',
    lead: 'Operate Security with Continuous Governance',
    intro: 'Security posture is not a project — it is an operational discipline. Gigamatics delivers continuous security monitoring, vulnerability governance, access control oversight, incident detection, and compliance management as a structured managed service.',
    pillarsIntro: 'Every Gigamatics security managed service is structured around defined operational pillars — each documented, governed, and adapted to your technology environment, threat profile, and compliance obligations.',
    pillars: [
      { title: 'Continuous Security Posture Monitoring', body: 'Ongoing measurement of security posture across cloud, identity, network, and endpoint layers.', includes: ['CSPM integration', 'Control effectiveness tracking', 'Posture score trending', 'Misconfiguration alerting'] },
      { title: 'Vulnerability Scanning & Patch Validation', body: 'Scheduled and continuous scanning with patch validation to confirm remediation is effective.', includes: ['Automated scanning', 'CVSS prioritisation', 'Patch status tracking', 'Post-patch validation'] },
      { title: 'Access Control & Privilege Governance', body: 'Regular reviews of users, roles, and privileges ensuring least-privilege is enforced.', includes: ['Permission review cycles', 'Privileged access governance', 'Service account lifecycle', 'Dormant account remediation'] },
      { title: 'Security Incident Detection', body: 'Structured detection, triage, and escalation with defined severity classifications and RCA.', includes: ['Alert triage', 'P1/P2/P3 SLAs', 'Senior engineer escalation', 'Post-incident RCA'] },
      { title: 'Compliance Monitoring & Reporting', body: 'Continuous monitoring against SOC 2, ISO 27001, HIPAA, PCI-DSS, and GDPR.', includes: ['Control monitoring', 'Gap identification', 'Monthly compliance reports', 'Multi-framework coverage'] },
      { title: 'Audit Preparation & Evidence', body: 'Systematic collection and maintenance of audit evidence so you enter every review prepared.', includes: ['Evidence cataloguing', 'Framework-specific packages', 'Live audit support', 'Auditor query coordination'] },
    ],
    engagementPhases: [
      { title: 'Named Senior Security Engineer Ownership', body: 'Assigned to a named senior security engineer who understands your architecture and compliance obligations.' },
      { title: 'Structured Onboarding & Security Baseline', body: 'Comprehensive baseline assessment documenting attack surface, control gaps, and risk exposure.' },
      { title: 'Contractually Defined SLAs', body: 'Incident response times, posture monitoring standards, and reporting deadlines are contractually bound.' },
      { title: 'Monthly Security & Compliance Reports', body: 'Posture score, incidents, vulnerability status, patch compliance, and control status.' },
      { title: 'Compliance Advisory Included', body: 'Framework interpretation and audit preparation support are part of the engagement.' },
    ],
    principles: [
      { title: 'Senior Security Engineers', body: 'Managed by engineers who have designed security architectures and responded to real incidents at enterprise scale.' },
      { title: 'Compliance Embedded in Operations', body: 'Evidence collection and control monitoring are built into day-to-day operations — so you are always audit-ready.' },
      { title: 'Proactive Posture', body: 'Continuous monitoring and vulnerability management cadences close risks before they become exploitable.' },
      { title: 'Multi-Framework Capability', body: 'SOC 2, ISO 27001, HIPAA, PCI-DSS, and GDPR under a single operational engagement.' },
    ],
  },
  {
    slug: 'platform',
    path: '/managed-services/platform',
    title: 'Managed Platform Reliability & Performance',
    cardBody: 'Proactive performance monitoring, capacity planning, incident coordination and operational improvements.',
    lead: 'Operate Platforms with Continuous Reliability',
    intro: 'Platform reliability is not a state you reach — it is an ongoing operational practice. Gigamatics delivers SRE-principled managed operations: proactive performance monitoring, SLO governance, capacity planning, incident coordination, and observability engineering.',
    pillarsIntro: 'Structured operational pillars — each documented, governed, and calibrated to your platform architecture, SLO targets, and engineering team’s working model.',
    pillars: [
      { title: 'Proactive Performance Monitoring', body: 'Continuous monitoring of latency, throughput, error rates, saturation, and availability with anomaly-driven alerting.', includes: ['Metric collection and dashboards', 'Alert threshold tuning', 'Anomaly detection', 'Weekly trend analysis'] },
      { title: 'SLO Tracking & Error Budgets', body: 'Define, instrument, and track Service Level Objectives with error budget accounting for clear ship-vs-stabilize signals.', includes: ['SLI/SLO workshops', 'Real-time SLO dashboards', 'Burn rate alerting', 'Monthly SLO reports'] },
      { title: 'Capacity Planning & Scaling', body: 'Forward-looking capacity analysis translating growth projections into provisioning recommendations.', includes: ['Utilisation trending', 'Capacity forecasting', 'Scaling threshold reviews', 'Quarterly capacity reports'] },
      { title: 'Incident Coordination & Response', body: 'Structured incident response with a named senior SRE coordinating containment, communication, and RCA.', includes: ['Severity classification', 'Named SRE ownership', 'Stakeholder communication', 'Blameless RCA'] },
      { title: 'Observability Optimisation', body: 'Continuous improvement of metrics, logs, and traces so observability actually informs reliability decisions.', includes: ['Coverage audits', 'Instrumentation gap remediation', 'Dashboard rationalisation', 'Alert fatigue reduction'] },
      { title: 'Runbook Maintenance', body: 'Continuous maintenance of operational runbooks and incident playbooks — current, tested, and accessible.', includes: ['Runbook creation', 'Quarterly accuracy review', 'Playbook updates', 'Knowledge transfer sessions'] },
    ],
    engagementPhases: [
      { title: 'Named Senior SRE Ownership', body: 'Your platform is owned by a named senior reliability engineer — not a rotating on-call pool.' },
      { title: 'SLO Framework & Observability Onboarding', body: 'SLI/SLO definitions, observability audit, alert calibration, and runbook documentation before operations begin.' },
      { title: 'Contractually Bound Response SLAs', body: 'P1 response within 15 minutes, SLO monitoring 24×7, and monthly performance reporting.' },
      { title: 'Monthly Reliability Report', body: 'SLO attainment, error budget consumption, incidents, capacity status, and improvement recommendations.' },
      { title: 'Continuous Improvement Cadence', body: 'Operational recommendations, runbook updates, and alert recalibration delivered monthly.' },
    ],
    principles: [
      { title: 'SLOs Over Uptime Percentages', body: 'We move from vague five-nines aspirations to precisely defined, measured Service Level Objectives.' },
      { title: 'Error Budgets Over Feature Freezes', body: 'Error budgets give leadership a quantitative framework for balancing reliability and velocity.' },
      { title: 'Proactive Over Reactive', body: 'Capacity forecasting and operational improvement shift orientation from responding to preventing incidents.' },
      { title: 'Senior SREs, Not NOC Analysts', body: 'Operated by engineers who have designed distributed systems and built SLO frameworks at scale.' },
    ],
  },
];

export function getManaged(slug) {
  return MANAGED_SERVICES.find((s) => s.slug === slug);
}
