export const SERVICES_OVERVIEW = {
  eyebrow: 'Service Portfolio',
  title: 'Enterprise Technology Services',
  lead: 'End-to-end consulting, implementation, and advisory services across cloud, data, security, disaster recovery, platform operations, and intelligent automation. Each engagement is practitioner-led, outcome-defined, and structured for long-term platform integrity.',
  stats: [
    { value: '6', label: 'Core Service Domains' },
    { value: '3', label: 'Delivery Modes' },
    { value: '100%', label: 'Senior-Led Engagements' },
  ],
  capabilitiesIntro: {
    eyebrow: 'Our Capabilities',
    title: 'What We Design, Implement & Govern',
    body: 'Gigamatics brings structured, senior-led expertise to the technology domains that determine enterprise resilience, operational continuity, and competitive readiness.',
  },
  phases: [
    { title: 'Assess & Discover', body: 'Structured review of your current landscape architecture, controls, gaps, risk exposure, and operational maturity. Outputs include a documented findings report and prioritized risk register.' },
    { title: 'Design & Architect', body: 'We design the target state — platform architecture, governance frameworks, security controls, and implementation blueprints aligned to your business objectives and constraints.' },
    { title: 'Implement & Deliver', body: 'Structured execution of approved designs with defined milestones, change governance, and senior oversight at every stage. Delivery is accountable, not delegated.' },
    { title: 'Operate & Sustain', body: 'Post-implementation managed operations, monitoring, continuous improvement, and advisory support — governed by the same standards defined during the consulting phase.' },
  ],
  deliverables: [
    { title: 'Architecture & Design Documents', body: 'Detailed technical blueprints, decision rationale, and implementation-ready specifications.' },
    { title: 'Risk Registers & Governance Frameworks', body: 'Prioritized risk documentation, control matrices, and enforceable governance structures.' },
    { title: 'Runbooks, Playbooks & SOPs', body: 'Operational documentation your teams can execute and your auditors can review.' },
    { title: 'Milestone Reports & Progress Summaries', body: 'Structured progress documentation for executive stakeholders and project governance.' },
  ],
  outcomes: [
    { num: '01', title: 'We Think Before We Build', body: 'Every implementation begins with a structured assessment. We do not deploy before we understand. Architecture decisions, governance requirements, and risk tolerances are defined before a single configuration change is made.' },
    { num: '02', title: 'We Govern Before We Scale', body: 'Scaling without governance creates technical debt, compliance exposure, and operational fragility. We build controls, policies, and guardrails first — ensuring every platform that scales does so within a defined operating model.' },
    { num: '03', title: 'We Design Systems That Endure', body: 'Our goal is not a successful go-live. It is a platform that performs under pressure, survives team changes, passes audits, and remains maintainable three years after implementation. Endurance is the design standard.' },
    { num: '04', title: 'We Stay Accountable Beyond Delivery', body: 'We do not disappear after implementation. Whether through structured transition, managed operations, or advisory continuity, we remain accountable to the architecture, standards, and outcomes defined during engagement.' },
  ],
  deliveryTable: [
    { domain: 'Cloud & Infrastructure', consulting: 'Architecture Design', implement: 'Migration & Deployment', managed: 'Cloud Ops' },
    { domain: 'Data Modernization', consulting: 'Platform Strategy', implement: 'Pipeline Build & Migration', managed: 'DB Operations' },
    { domain: 'Security, Risk & Compliance', consulting: 'Posture Assessment', implement: 'Controls Implementation', managed: 'Security Ops' },
    { domain: 'Disaster Recovery & Continuity', consulting: 'Recovery Architecture', implement: 'DR Build & Validation', managed: 'Continuity Monitoring' },
    { domain: 'Platform Reliability', consulting: 'SRE Assessment', implement: 'Observability Buildout', managed: 'Platform Ops' },
    { domain: 'AI & Automation', consulting: 'AI Readiness Design', implement: 'Pipeline & Model Deployment', managed: 'Model Ops' },
  ],
};

export const SERVICES = [
  {
    slug: 'data-modernization',
    path: '/services/data-modernization',
    title: 'Data Modernization & Analytics',
    shortTitle: 'Data Modernization & Analytics',
    cardBody: 'Transform legacy data estates into intelligent, cloud-native platforms. We architect data lakes, pipelines, and BI capabilities that turn raw data into strategic decisions.',
    cardIncludes: ['Data lakes, pipelines & BI', 'Governance & quality frameworks', 'Lakehouse architecture'],
    lead: 'Data Platforms Built for Trust, Scale & Intelligence',
    intro: 'We design, migrate, and govern enterprise data platforms — from legacy warehouse modernisation and Lakehouse architecture to pipeline engineering, analytics enablement, and data governance frameworks built for long-term operational use.',
    pillarsIntro: 'Modern data challenges are no longer limited to reporting. Organizations today struggle with aging databases, rising cloud costs, inconsistent data quality, slow analytics, and platforms that cannot scale with business growth. We help enterprises modernize databases, migrate data platforms to the cloud, improve performance, and enable analytics — with ownership from assessment through stable operations.',
    pillars: [
      { title: 'Data Platform Modernization', body: 'Modernize legacy data warehouses and analytics systems into scalable, cloud-ready platforms designed for modern data workloads.', includes: ['Legacy warehouse modernization', 'Cloud data platform architecture', 'Platform consolidation & migration', 'Performance and scalability optimization'] },
      { title: 'Lakehouse Architecture', body: 'Design unified lakehouse platforms that combine the flexibility of data lakes with the performance and reliability of data warehouses.', includes: ['Lakehouse architecture design', 'Storage and compute selection', 'Analytics and BI integration', 'Governance and performance frameworks'] },
      { title: 'Data Pipeline Engineering', body: 'Build reliable batch and streaming pipelines that move data across systems with monitoring, validation, and operational stability.', includes: ['Batch and streaming pipeline design', 'ETL / ELT architecture', 'Validation and reconciliation', 'Pipeline monitoring and error handling'] },
      { title: 'Analytics & BI Enablement', body: 'Implement analytics platforms and reporting layers that transform enterprise data into consistent, trusted business insights.', includes: ['Semantic and dimensional models', 'BI platform architecture', 'KPI frameworks and standards', 'Dashboard performance optimization'] },
      { title: 'Data Governance & Quality', body: 'Establish governance frameworks that ensure trusted data through ownership models, quality controls, and access governance.', includes: ['Ownership and stewardship', 'Quality monitoring and rules', 'Lineage and metadata management', 'Access governance and policies'] },
      { title: 'Master Data Management', body: 'Design master data frameworks that maintain consistent and authoritative records across enterprise systems.', includes: ['Entity and domain modeling', 'MDM platform architecture', 'Matching and survivorship rules', 'Master data lifecycle governance'] },
    ],
    engagementPhases: [
      { title: 'Current State Assessment & Data Strategy', body: 'Auditing the existing data estate — source systems, data flows, warehouse architecture, data quality, governance maturity, and analytics consumption patterns — to define a risk-aware modernisation strategy.' },
      { title: 'Platform Architecture & Foundation Design', body: 'Designing the target-state data platform — platform selection, lakehouse or warehouse architecture, zone structure, pipeline framework, governance model, and access control design.' },
      { title: 'Pipeline Engineering & Platform Build', body: 'Building data pipelines, transformation models, data catalogue integrations, and BI foundations — with data quality checks embedded at every layer.' },
      { title: 'Analytics Enablement & Operational Handover', body: 'Standing up the analytics and BI layer, delivering operational runbooks, governance documentation, and data team knowledge transfer.' },
    ],
    principles: [
      { title: 'Architecture First', body: 'Platform selection, zone structure, modelling conventions, access control patterns, and pipeline frameworks are decided — and documented — before a single pipeline is built.' },
      { title: 'Governed by Design', body: 'Data ownership, quality rules, classification, and lineage are structural properties of the platform, enforced by design rather than retrofitted later.' },
      { title: 'Optimised for Insight', body: 'We design every layer — ingestion, storage, transformation, serving — with the consuming use case in mind.' },
      { title: 'Operationally Sustainable', body: 'Clear naming conventions, documented pipeline logic, runbook coverage, and knowledge transfer leave your data team genuinely capable.' },
    ],
  },
  {
    slug: 'cloud-infrastructure',
    path: '/services/cloud-infrastructure',
    title: 'Cloud & Infrastructure',
    shortTitle: 'Cloud & Infrastructure',
    cardBody: 'Assess, migrate, modernise, and optimise your cloud footprint across AWS, Azure, Oracle and GCP — with governance and cost optimisation.',
    cardIncludes: ['Architecture assessment & modernization', 'Multi-cloud & hybrid infrastructure', 'Cost optimization & FinOps', 'Infrastructure-as-Code'],
    lead: 'Cloud Platforms Built for Stability, Scale & Control',
    intro: 'We help enterprises design, migrate, and govern cloud and infrastructure platforms with clarity, architectural rigour, and defined ownership — from assessment through stable production operations.',
    pillarsIntro: 'Modern cloud challenges extend far beyond infrastructure provisioning. Organizations face legacy on-prem environments, fragmented architectures, rising cloud costs, inconsistent governance, and platforms that struggle to scale. Cloud transformation is not a tooling initiative; it is the design and operation of secure, scalable, and cost-efficient platforms.',
    pillars: [
      { title: 'Cloud Strategy & Advisory', body: 'Assessment of infrastructure, application dependencies, and regulatory requirements to define the right public, private, or hybrid cloud model.', includes: ['Architecture and roadmap', 'Cloud model selection', 'Target operating model'] },
      { title: 'Landing Zone & Platform Design', body: 'Secure foundations, account structure, and guardrails for enterprise cloud environments.', includes: ['Landing zone design', 'Account structure', 'Security guardrails'] },
      { title: 'Cloud Migration Services', body: 'Planned execution of application, data, and infrastructure migrations using phased waves and dependency mapping.', includes: ['Phased wave planning', 'Dependency mapping', 'Controlled cut-over', 'Post-migration validation'] },
      { title: 'Network & Connectivity Architecture', body: 'Design of network and connectivity patterns across on-premises and cloud environments.', includes: ['VPC and segmentation', 'IAM and policy enforcement', 'Hybrid connectivity'] },
      { title: 'FinOps & Cost Governance', body: 'Implementation of cost allocation, usage visibility, and optimization controls for predictable spend.', includes: ['Cost allocation', 'Spend control', 'Optimisation cadence'] },
      { title: 'Managed Cloud Operations', body: 'Ongoing monitoring, incident management, and performance optimization with defined accountability.', includes: ['Production monitoring', 'Incident management', 'Continuous improvement'] },
    ],
    engagementPhases: [
      { title: 'Cloud Assessment & Strategic Direction', body: 'Evaluating existing infrastructure, workloads, network architecture, security posture, and cloud readiness to define a clear modernization strategy.' },
      { title: 'Cloud Platform Modernization & Migration', body: 'Establishing secure cloud landing zones and executing structured workload migrations to production-ready environments.' },
      { title: 'Cloud Architecture & Operational Enablement', body: 'Designing resilient architectures, identity models, connectivity frameworks, and governance controls.' },
      { title: 'Cloud Performance, Cost & Reliability Optimization', body: 'Optimizing workloads, controlling spend through FinOps practices, and engineering high-availability environments.' },
    ],
    principles: [
      { title: 'Proactive by Design', body: 'Capacity, cost, and operational risks are evaluated during the architecture phase — before infrastructure is provisioned.' },
      { title: 'Built for Stability', body: 'Architectures are designed for resilience and recovery — validated against real production traffic patterns and failure scenarios.' },
      { title: 'Secure by Design', body: 'Identity, access controls, network segmentation, and policy enforcement are embedded at the platform foundation.' },
      { title: 'Defined Ownership', body: 'Every component has a defined owner, a documented operating model, and a clear handover process.' },
    ],
  },
  {
    slug: 'security-risk-compliance',
    path: '/services/security-risk-compliance',
    title: 'Risk, Security & Compliance',
    shortTitle: 'Risk, Security & Compliance',
    cardBody: 'From threat modelling to compliance frameworks and Zero Trust architecture, we protect your systems, data, and reputation.',
    cardIncludes: ['Security posture assessment', 'Zero-trust architecture', 'Compliance & audit readiness', 'Risk registers & governance'],
    lead: 'Security Embedded into Platform Architecture — Not Bolted On',
    intro: 'We design, implement, and govern enterprise security programmes — embedding controls, governance frameworks, and risk management practices into your technology platform from the foundation up, not as an audit afterthought.',
    pillarsIntro: 'Security and compliance should not be treated as isolated initiatives or periodic audit exercises. They are core design and operational disciplines that must be embedded into the way technology platforms are built and operated.',
    pillars: [
      { title: 'Security Architecture & Design', body: 'Comprehensive security architecture blueprints covering identity models, network design, encryption standards, and enforceable control frameworks.', includes: ['Zero Trust strategy', 'IAM framework design', 'Network segmentation', 'Encryption standards'] },
      { title: 'Cloud Security Posture Management', body: 'Cloud security assessment and guardrail implementation across multi-cloud environments.', includes: ['Posture assessment', 'Least-privilege enforcement', 'Policy guardrails', 'CIS baseline alignment'] },
      { title: 'Risk Management & Assessment', body: 'Enterprise risk assessments aligned to recognised frameworks — documenting exposure and defining structured mitigation roadmaps.', includes: ['Security risk assessment', 'Threat modelling', 'Risk register creation', 'Mitigation planning'] },
      { title: 'Compliance Readiness & Certification', body: 'End-to-end compliance support — from framework mapping and control design to evidence collection and pre-audit validation.', includes: ['Gap assessment', 'Control design', 'Policy documentation', 'Audit readiness'] },
      { title: 'Vulnerability Management Programme', body: 'A disciplined vulnerability lifecycle — scan coverage, risk-based prioritisation, remediation tracking, and executive reporting.', includes: ['Scanning design', 'Risk prioritisation', 'Remediation SLAs', 'Executive reporting'] },
      { title: 'Security Policy & Governance Design', body: 'Structured governance frameworks defining accountability, enforcement mechanisms, and measurable security oversight.', includes: ['Policy hierarchy', 'Security RACI', 'Exception workflows', 'KRI reporting'] },
    ],
    engagementPhases: [
      { title: 'Security & Risk Assessment', body: 'Structured evaluation of cloud configuration, identity controls, network architecture, data protection, vulnerability landscape, and compliance gaps.' },
      { title: 'Security Architecture & Control Framework Design', body: 'Design of target-state security architecture — identity model, network controls, data protection, cloud guardrails, and governance structure.' },
      { title: 'Control Implementation & Audit Readiness', body: 'Structured implementation of security controls with evidence collection built into each control from the start.' },
    ],
    principles: [
      { title: 'Architecture First', body: 'Security controls are architectural decisions, not operational additions. We design them into the platform foundation.' },
      { title: 'Risk-Led Decisions', body: 'Security investment is guided by measured risk — not checkbox compliance.' },
      { title: 'Enforceable Controls', body: 'Controls that can be violated are not controls. We design technically enforced guardrails wherever possible.' },
      { title: 'Operational Stability', body: 'Security programmes that endure are proportionate, integrated into workflows, and realistically resourced.' },
    ],
  },
  {
    slug: 'disaster-recovery',
    path: '/services/disaster-recovery',
    title: 'Disaster Recovery & Business Continuity',
    shortTitle: 'Disaster Recovery & Continuity',
    cardBody: 'Design, test, and manage resilient DR strategies across on-premise, hybrid, and multi-cloud environments. Zero compromise on uptime.',
    cardIncludes: ['RTO/RPO-driven architecture', 'DR runbooks & failover testing', 'Backup strategy', 'Business continuity planning'],
    lead: 'Designing Recovery Capabilities for Sustained Availability',
    intro: 'We design, validate, and operationalise enterprise disaster recovery and business continuity programmes — engineering measurable RTO/RPO outcomes, proven failover capability, and organisational readiness for the moments that matter most.',
    pillarsIntro: 'Resilience is not a single tool or backup job — it is an engineered capability. We align recovery design with real business impact — identifying critical systems, defining acceptable downtime, and engineering recovery paths that work under pressure.',
    pillars: [
      { title: 'DR Architecture & Failover Design', body: 'Designing recovery architectures that meet defined RTO/RPO targets across cloud and hybrid environments.', includes: ['Recovery pattern selection', 'Replication strategy', 'Failover routing design', 'DR environment build'] },
      { title: 'RTO/RPO Engineering & Gap Closure', body: 'Evaluating whether current architecture can meet recovery aspirations — and building what is needed to close the gap.', includes: ['Capability assessment', 'Gap analysis', 'Remediation roadmap', 'Validated target-state architecture'] },
      { title: 'Business Continuity Planning', body: 'BCP frameworks aligned to real operational dependencies, structured for practical activation under pressure.', includes: ['Business Impact Analysis', 'BCP documentation', 'Dependency mapping', 'ISO 22301 alignment'] },
      { title: 'DR Testing & Failover Validation', body: 'Structured testing from tabletops to live failover tests that validate actual recovery capability.', includes: ['Tabletop facilitation', 'Live failover testing', 'Recovery time measurement', 'Post-test remediation'] },
      { title: 'Crisis & Incident Playbooks', body: 'Operationally precise runbooks, role-specific decision trees, and communication protocols for crisis response.', includes: ['Technical recovery runbooks', 'Escalation paths and RACI', 'Communications templates', 'Executive status frameworks'] },
      { title: 'DR Programme Governance', body: 'Ongoing assurance frameworks — testing schedules, audit evidence, and maturity improvement roadmaps.', includes: ['Testing programme calendar', 'Audit evidence packages', 'Maturity assessment', 'Board reporting'] },
    ],
    engagementPhases: [
      { title: 'Current-State Resilience Assessment', body: 'Architecture review, RTO/RPO gap analysis, dependency mapping, and BCP documentation audit.' },
      { title: 'Architecture & Programme Design', body: 'Target-state DR architecture, failover patterns, BCP framework, and crisis playbook structure.' },
      { title: 'DR Environment Build & Documentation', body: 'Recovery environments, replication pipelines, failover routing, and complete runbook documentation.' },
      { title: 'Testing, Failover Exercises & Certification', body: 'Tabletops, controlled failover tests, and measured validation of RTO/RPO performance.' },
      { title: 'Operational Readiness & Programme Governance', body: 'Formal handover of documentation, testing schedules, governance frameworks, and knowledge transfer.' },
    ],
    principles: [
      { title: 'Designed Recovery', body: 'RTO and RPO are engineering constraints that drive architecture decisions — not aspirational targets.' },
      { title: 'Assumed Failure', body: 'Failures are design inputs. Every dependency is a potential single point of failure until protected.' },
      { title: 'Validated Execution', body: 'An untested recovery plan is not a recovery plan. We validate through structured testing.' },
      { title: 'Operational Readiness', body: 'Crisis response is a skill that decays without practice. Recovery discipline is practised, not assumed.' },
    ],
  },
  {
    slug: 'platform-reliability',
    path: '/services/platform-reliability',
    title: 'Platform Reliability, Performance & Optimization',
    shortTitle: 'Platform Reliability & Performance',
    cardBody: 'Eliminate instability, reduce mean time to recovery, and build observability frameworks for real-time platform health.',
    cardIncludes: ['SRE practices', 'Observability & incident management', 'Performance baselining', 'On-call design'],
    lead: 'Operating Resilient Platforms for Sustained Reliability',
    intro: 'Platform failures are not technology failures — they are architecture and process failures. We address reliability as a structured engineering engagement with measurable outputs: defined SLOs, observable failure signals, and structured incident response.',
    pillarsIntro: 'Systems that lack defined reliability targets, observable failure signals, and structured incident response will degrade under scale, regardless of the cloud provider or technology stack.',
    pillars: [
      { title: 'SRE Implementation & SLO Framework', body: 'Defining what good looks like, how it is measured, and what happens when the error budget runs out.', includes: ['SLI/SLO definition', 'Error budget policy', 'On-call design', 'SLA alignment'] },
      { title: 'Observability Architecture', body: 'Building observability into the platform so failure signals are clear, correlated, and actionable.', includes: ['Observability stack architecture', 'OpenTelemetry instrumentation', 'Golden signals dashboards', 'Distributed tracing'] },
      { title: 'Incident Management & Response', body: 'Structured incident response that reduces MTTR and generates learning that prevents recurrence.', includes: ['Severity tiers and escalation', 'Runbooks and commander roles', 'Blameless PIR/RCA', 'Incident tooling'] },
      { title: 'Performance Engineering', body: 'Identifying root constraints at application, infrastructure, or data layer and engineering durable improvements.', includes: ['Performance baselining', 'Latency profiling', 'Load testing', 'Caching and query optimisation'] },
      { title: 'Capacity Planning & Scaling', body: 'Capacity models and scaling architectures that match growth ahead of demand.', includes: ['Traffic growth modelling', 'Auto-scaling policy design', 'Saturation thresholds', 'Scale constraint review'] },
      { title: 'Reliability Governance', body: 'Operating model, review cadence, and accountability structures that keep reliability a first-class concern.', includes: ['Production readiness reviews', 'SLO reporting cadence', 'Chaos engineering programme', 'Reliability RACI'] },
    ],
    engagementPhases: [
      { title: 'Reliability Baseline', body: 'Incident history analysis, MTTR/MTTD measurement, SLO gap assessment, and observability coverage audit.' },
      { title: 'SLO Framework & Observability Design', body: 'SLI/SLO definitions, error budget policies, observability stack architecture, and incident response processes.' },
      { title: 'Instrumentation & Process Rollout', body: 'Observability instrumentation, SLO dashboards, alerting, incident tooling, and on-call rotation design.' },
      { title: 'Validation & Sustained Improvement', body: 'Load testing, chaos exercises, SLO burn rate validation, and MTTR benchmarking against baseline.' },
    ],
    principles: [
      { title: 'Define Before You Measure', body: 'Reliability targets must be defined from user expectations first, then instrumentation measures whether they are met.' },
      { title: 'Error Budgets as Policy', body: 'Error budgets turn reliability into a shared engineering discipline between velocity and stability.' },
      { title: 'Observability vs Monitoring', body: 'Monitoring tells you something is wrong. Observability tells you why.' },
      { title: 'Reliability Without Toil', body: 'Manual operational work that scales with traffic is an engineering liability. We design for toil reduction.' },
    ],
  },
  {
    slug: 'ai-automation',
    path: '/services/ai-automation',
    title: 'AI & Intelligent Automation',
    shortTitle: 'AI & Intelligent Automation',
    cardBody: 'Embed AI-driven workflows, predictive models, and process automation — practical, scalable, and aligned to business outcomes.',
    cardIncludes: ['AI readiness & use-case design', 'ML pipeline architecture', 'Intelligent process automation', 'AI governance & model ops'],
    lead: 'Built for Intelligence. Designed for Automation Efficiency',
    intro: 'We design and implement enterprise AI and intelligent automation programmes — translating AI potential into structured, governed, measurable capability. Not pilots that don’t scale, but AI systems that integrate into operations, produce auditable outputs, and improve as your business grows.',
    pillarsIntro: 'Most AI initiatives fail not because the models are wrong, but because the surrounding architecture is not ready. Data quality is insufficient, governance is absent, and the business case was never precise enough to measure. We address AI as a systems engineering problem.',
    pillars: [
      { title: 'AI Strategy & Use Case Prioritisation', body: 'Technology-agnostic AI strategy that begins with business outcomes and works backwards to use cases and technology choices.', includes: ['Opportunity assessment', 'Use case prioritisation', 'Build vs buy framework', 'Phased AI roadmap'] },
      { title: 'Generative AI & LLM Integration', body: 'Production LLM systems with prompt engineering, retrieval architecture, evaluation frameworks, and latency controls.', includes: ['RAG architecture', 'LLM orchestration', 'Prompt guardrails', 'LLM evaluation'] },
      { title: 'Machine Learning & Predictive Analytics', body: 'End-to-end ML system design from feature engineering through production serving with monitoring.', includes: ['Feature engineering', 'Model training', 'Serving architecture', 'Drift detection'] },
      { title: 'Intelligent Process Automation', body: 'IPA combines RPA execution with AI-powered decision-making for processes that require classification and judgment.', includes: ['Process mapping', 'Document intelligence', 'AI-augmented RPA', 'Orchestration frameworks'] },
      { title: 'MLOps & AI Platform Engineering', body: 'The engineering discipline that makes production AI systems reproducible, observable, and maintainable.', includes: ['ML platform design', 'CI/CD for ML', 'Model monitoring', 'Experiment tracking'] },
      { title: 'AI Governance, Risk & Compliance', body: 'AI governance designed into the system — model cards, audit trails, bias evaluation, and human oversight.', includes: ['AI risk assessment', 'Governance framework', 'Regulatory alignment', 'Acceptable use policy'] },
    ],
    engagementPhases: [
      { title: 'Business Outcome Definition & Opportunity Assessment', body: 'Prioritised use case register with business case, feasibility score, data readiness, and sequencing strategy.' },
      { title: 'AI Architecture Design & Data Readiness', body: 'Target-state AI architecture — model selection, data pipelines, serving, MLOps platform, and governance controls.' },
      { title: 'Model Development & Integration', body: 'Feature engineering, model training, evaluation against defined thresholds, and integration into operations. Every model ships with a model card.' },
      { title: 'Production Deployment & Observability', body: 'Canary rollout, A/B validation, drift detection thresholds, retraining triggers, and operational runbooks.' },
    ],
    principles: [
      { title: 'Outcome Before Technology', body: 'The right question is not what AI we can use — it is what problem we are solving.' },
      { title: 'The Notebook-to-Production Gap', body: 'A model that works in a notebook is not a production AI system. MLOps is the architecture that makes it useful.' },
      { title: 'LLMs Are Not Magic', body: 'Generative AI requires the same engineering discipline as any other production system.' },
      { title: 'Governance Is Architecture', body: 'AI governance is an engineering requirement — not a compliance checkbox.' },
    ],
  },
  {
    slug: 'finops',
    path: '/services/finops',
    title: 'FinOps & Cloud Cost Optimisation',
    shortTitle: 'FinOps & Cloud Cost Optimisation',
    cardBody: 'Structured FinOps practice for full visibility, enforceable governance, and measurable sustained cost reduction — without sacrificing performance.',
    cardIncludes: ['Cost visibility & allocation', 'Rightsizing', 'Commitment strategy', 'FinOps governance'],
    lead: 'Run Technology with Financial Intelligence and Control',
    intro: 'Cloud spend is often your second or third largest technology cost — and most organisations waste 25–35% of it. Gigamatics brings a structured FinOps practice for full visibility, enforceable governance, and measurable sustained cost reduction — without sacrificing performance or velocity.',
    pillarsIntro: 'FinOps is not a cost-cutting exercise. It is a financial operating model for cloud — bringing engineering, finance, and operations together to make deliberate decisions about cloud spend at scale.',
    pillars: [
      { title: 'Cloud Cost Visibility & Allocation', body: 'A complete, accurate view of cloud spend mapped to the teams, products, and workloads that generate it.', includes: ['Tagging strategy', 'Cost allocation framework', 'Showback and chargeback', 'Anomaly alerting'] },
      { title: 'Rightsizing & Resource Optimisation', body: 'Systematically identify over-provisioned and underutilised resources and right-size them without degrading performance.', includes: ['Utilisation analysis', 'Rightsizing recommendations', 'Auto-scaling review', 'Continuous rightsizing cadence'] },
      { title: 'Commitment & Savings Plan Strategy', body: 'The right mix of Reserved Instances, Savings Plans, and spot usage without over-committing.', includes: ['Commitment spend analysis', 'RI portfolio design', 'Savings Plans / CUDs', 'Utilisation monitoring'] },
      { title: 'Waste Elimination & Remediation', body: 'Identify and eliminate idle, orphaned, and zombie cloud resources that silently drain spend.', includes: ['Idle workload identification', 'Orphaned storage cleanup', 'Dev/test spend governance', 'Automated waste detection'] },
      { title: 'FinOps Governance Framework', body: 'Policies, budgets, guardrails, and accountability structures that make cost optimisation continuous.', includes: ['Budget design', 'Cost guardrails', 'Anomaly detection', 'Monthly review cadence'] },
      { title: 'FinOps Maturity Assessment', body: 'Structured evaluation of visibility, accountability, tooling, and optimisation practice with a prioritised roadmap.', includes: ['Maturity scoring', 'Gap analysis', 'Tooling evaluation', 'Savings potential estimates'] },
    ],
    engagementPhases: [
      { title: 'Cloud Cost Baseline & Assessment', body: 'Full analysis of spend by service, team, region, and workload — with savings opportunity estimates by category.' },
      { title: 'Visibility Architecture & Tagging Framework', body: 'Tagging strategy, cost allocation model, and dashboards for engineering and finance.' },
      { title: 'Optimisation Sprints & Waste Remediation', body: 'Structured sprints targeting rightsizing, waste elimination, and commitment purchasing with validated savings.' },
      { title: 'Governance Framework & Operating Model', body: 'Policies, budgets, guardrails, and review cadences embedded into team workflows.' },
    ],
    principles: [
      { title: 'Engineering-Led, Not Finance-Led', body: 'Cost decisions involve trade-offs between performance, reliability, and velocity. Our practice is led by cloud architects.' },
      { title: 'Savings That Are Actually Realised', body: 'Every recommendation is validated, risk-classified, and implemented — with before-and-after savings confirmed.' },
      { title: 'Governance That Outlasts Engagement', body: 'Frameworks and accountability structures sustain cost discipline after we leave.' },
      { title: 'Connected to Broader Cloud Strategy', body: 'FinOps integrates with architecture, security posture, and platform strategy — not in isolation.' },
    ],
  },
];

export function getService(slug) {
  return SERVICES.find((s) => s.slug === slug);
}
